add get_last_lr to WarmupCosineLR
Current implementation of WarmupCosineLR does not have `get_last_lr()` function, so that downstream applications encounter `AttributeError: 'WarmupCosineLR' object has no attribute 'get_last_lr'. Did you mean: '_last_lr'?`